#### 1.Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [29]:
import numpy as np
l=[1,2,3,4]

def vandermonde(l,N=len(l),increasing=False):
    b=[]
    new=[]
    for i in range(len(l)):
        a=[]
        
        #Block for Number of columns user want Default N will be len(Given List)/ 1-d array
        
        for j in range(N):
            a.append(l[i]**j)
        b.append(a)
        
    '''
    Conditional Block based on the user for Output
    If True, the powers increase from left to right, else will take default matrix output.
    '''
    if (increasing):
        return np.array(b)
    else:
        
        for i in range(len(b)):
            new.append((b[i][::-1]))
        return np.array(new)
        
        
        


In [30]:
#Scenario 1 Let increase =True 
vandermonde(l,N=5,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256]])

In [31]:
#Scenario 2 Let increase =Flase 
vandermonde(l,N=5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [33]:
#Scenario 3 Let increase =True and User input for N
N=int(input("Enter N 'Number of columns in the output.':"))
vandermonde(l,N,increasing=True)

Enter N 'Number of columns in the output.':6


array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024]])

In [34]:
#Scenario 4 Let increase =False and User input for N
N=int(input("Enter N 'Number of columns in the output.':"))
vandermonde(l,N)

Enter N 'Number of columns in the output.':4


array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

#### 2.Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [39]:
import numpy as np

def moving_avg(l):
    a=[]
    n= 3
    for i in range(len(l)-n+1):
        a.append(round(sum(np.array(l)[i:i+n]/n),2))
    return a
l=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]


In [40]:
moving_avg(l)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]